specfm/spec-next

config/sponsors.js

Adding Manifold information to the sponsor page listing

Manifold Info

---

config/sponsors.js

Hey Brian, 
Did something go wrong with Manifold? Did I miss a step?

Need to upload both Manifold and Nevercode

---

config/sponsors.js

Can we schedule this to go live 11/28?

Adding duckduckgo to sponsor page

---

config/sponsors.js

Adding Discoverbot to the sponsor page

---

config/sponsors.js

Adding Readymag to sponsor listing

---

config/podcasts.js

@SarahMJack - for future reference, this config file is where we can easily change any of the settings :)

Update react podcast slug

---

config/sponsors.js

Adding Imagekit as sponsor

---

config/sponsors.js

Adding Infinite Red logo to sponsor listing

---

config/sponsors.js

Adding Gitprime to sponsor page - sponsor launched on 05/24

Adding Gitprime

---

config/sponsors.js

Blue Medora airs on September 24th on DNC

Adding Blue Medora to sponsor listings

---

config/sponsors.js

Update sponsors.js - Add Toptal

---

src/config/sponsors.js

Square is going live on 11/18/19

Adding Square To Sponsor Page

---

src/config/sponsors.js

need to fix the image uploaded

Adding Givewell to sponsor page

---

src/config/sponsors.js

Updating flywheel link -- new campaign launching tomorrow

Updating Flywheel Link

---

src/config/sponsors.js

Pathrise sponsorship kicks off Jan 3rd 2020

Adding Pathrise to sponsors

---

src/config/sponsors.js

Adding ProdPerfect to Sponsor Page

---

src/config/sponsors.js

Educative went live on 04/01/2020

Educative to Sponsor Page

---

src/config/sponsors.js

Float is sponsoring the Design Details podcast from May 6th - October 28th 2020.

Adding Float

---

src/config/sponsors.js

GitPrime requested we update their landing page this week.

Updating the GitPrime landing

---

src/config/sponsors.ts

Test Cafe to sponsor React Podcast starting 06/07

Adding Test Cafe

---

src/config/sponsors.ts

honey badger to kick off on 07/28/2020

adding honey badger to the sponsor list

---

src/config/sponsors.ts

I was a dummy and tried to upload a white image....to be fair I hadn't had coffee yet, so do with that what you will. Fixing my goof!!!!

updating deep source image file

---

src/config/sponsors.ts

Curiosity Stream is kicking off on Layout starting Friday, Oct.2nd 🚀

Adding CuriosityStream

---

src/config/sponsors.ts

Monday to kick off as a sponsor on Dev Tea 10/21/2020

Adding Monday.com to sponsor listing

---

src/config/sponsors.ts

Adding New Relic for kickoff on 11/04/2020

Adding New Relic To Sponsor Listing
